name = "bundle cart transform"
type = "cart_transform"
title = "bundle cart transform"
api_version = "unstable"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/bundle_cart_transform.wasm"
